name: "📚 latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour, on the hour

jobs:
  update_blogs:
    name: "Latest Blog Post"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: "Vinyl-Davyl" # Hashnode Username
          COUNT: 4 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://vinyldavyl.hashnode.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
