name: Latest blog post workflow
on:
  schedule:
  - cron: '0 2 * * *'  # Runs daily at 2am UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://vinyldavyl.hashnode.dev/rss.xml"
          item_exec: "post.title = post.title.toLowerCase();"
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit & Push changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes to commit"
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add README.md
            git commit -m "chore: update latest blog posts"
            git push
          fi
