name: 📚 Latest Blog Post workflow
on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight
  workflow_dispatch:

jobs:
  update-readme-with-hashnode-blog:
    name: Update README with latest Hashnode blog post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          npm install axios
          
      - name: Update README with latest blog post
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node -e "
          const axios = require('axios');
          const fs = require('fs');
          const { execSync } = require('child_process');
          
          async function updateReadme() {
            try {
              const response = await axios.post('https://api.hashnode.com/', {
                query: \`
                  query {
                    user(username: \"vinyldavyl\") {
                      publication {
                        posts(page: 0) {
                          title
                          slug
                          dateAdded
                          brief
                        }
                      }
                    }
                  }
                \`
              });
              
              const posts = response.data.data.user.publication.posts;
              if (posts.length > 0) {
                const latestPost = posts[0];
                const readmePath = 'README.md';
                let readmeContent = fs.readFileSync(readmePath, 'utf8');
                
                // Create blog post section if it doesn't exist
                if (!readmeContent.includes('## Latest Blog Post')) {
                  readmeContent += '\n\n## Latest Blog Post\n';
                }
                
                // Update the blog post section
                const blogPostContent = \`
### [\${latestPost.title}](https://vinyldavyl.hashnode.dev/\${latestPost.slug})
\${latestPost.brief}
\`;
                
                readmeContent = readmeContent.replace(
                  /## Latest Blog Post[\s\S]*?(?=##|$)/,
                  \`## Latest Blog Post\n\n\${blogPostContent}\`
                );
                
                fs.writeFileSync(readmePath, readmeContent);
                
                // Commit and push changes
                execSync('git config --global user.name "GitHub Action"');
                execSync('git config --global user.email "action@github.com"');
                execSync('git add README.md');
                execSync('git commit -m "Update latest blog post"');
                execSync('git push');
              }
            } catch (error) {
              console.error('Error:', error.message);
              process.exit(1);
            }
          }
          
          updateReadme();
          "
