name: 📚 Latest Blog Post workflow
on:
  schedule: 
    - cron: '0 0 * * *' # Runs once a day at midnight
  workflow_dispatch: 

jobs:
  update-readme-with-hashnde-blog:
    name: Update this repo's README with the latest hashnde blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://vinyldavyl.hashnode.dev/rss.xml"
          max_post_count: 1
          retry_count: 3
          retry_delay: 60
