name: Latest blog post workflow

on:
  schedule:
    # Run every day at 2am UTC
    - cron: "0 2 * * *"

  # Allow manual runs from GitHub Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://vinyldavyl.hashnode.dev/rss.xml"
          item_exec: "post.title = post.title.toLowerCase();"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "chore: update latest blog posts" || echo "No changes to commit"
          git push
